import type { Metadata } from 'next';
import Image from 'next/image';
import './globals.css';
import Navbar from '../components/Navbar';
import bg1 from '../public/dark-background-with-dynamic-shapes_23-2148865192.jpg';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-zinc-900 text-white">
        <Navbar />

        <div className="fixed inset-0 -z-10">
          <Image
            src={bg1}
            alt=""
            fill
            className="object-cover opacity-10"
          />
        </div>

        {children}
      </body>
    </html>
  );
}
